// <auto-generated />
using System;
using BuildOpsPlatform.RevitDataService.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuildOpsPlatform.RevitDataService.Migrations
{
    [DbContext(typeof(RevitDataDbContext))]
    partial class RevitDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Category", b =>
                {
                    b.Property<Guid>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryType")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RvtSnapshotId", "CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.DesignOption", b =>
                {
                    b.Property<Guid?>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DesignOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("DesignOptionUniqueId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("RvtSnapshotId", "DesignOptionId");

                    b.ToTable("DesignOptions");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Element", b =>
                {
                    b.Property<Guid>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int>("ElementId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("DesignOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("ElementUniqueId")
                        .HasColumnType("text");

                    b.Property<int?>("LevelId")
                        .HasColumnType("integer");

                    b.Property<int?>("StageId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeName")
                        .HasColumnType("text");

                    b.Property<int?>("WorksetId")
                        .HasColumnType("integer");

                    b.HasKey("RvtSnapshotId", "ElementId");

                    b.HasIndex("RvtSnapshotId", "CategoryId");

                    b.HasIndex("RvtSnapshotId", "DesignOptionId");

                    b.HasIndex("RvtSnapshotId", "LevelId");

                    b.HasIndex("RvtSnapshotId", "StageId");

                    b.HasIndex("RvtSnapshotId", "WorksetId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.ElementError", b =>
                {
                    b.Property<Guid>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ElementId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ErrorId")
                        .HasColumnType("uuid");

                    b.HasKey("RvtSnapshotId", "Id");

                    b.HasIndex("RvtSnapshotId", "ElementId");

                    b.HasIndex("RvtSnapshotId", "ErrorId");

                    b.ToTable("ElementErrors");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.ElementMaterial", b =>
                {
                    b.Property<Guid>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int>("ElementId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.HasKey("RvtSnapshotId", "ElementId", "MaterialId");

                    b.HasIndex("RvtSnapshotId", "MaterialId");

                    b.ToTable("ElementMaterials");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.ElementParameterValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ElementId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasValue")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProject")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTypeParameter")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParameterDbId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParameterGUID")
                        .HasColumnType("uuid");

                    b.Property<int?>("ParameterId")
                        .HasColumnType("integer");

                    b.Property<Guid>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StorageType")
                        .HasColumnType("integer");

                    b.Property<string>("UnitType")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RvtSnapshotId", "ElementId");

                    b.HasIndex("RvtSnapshotId", "ParameterDbId");

                    b.ToTable("ParameterValues");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.ElementView", b =>
                {
                    b.Property<Guid>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int>("ElementId")
                        .HasColumnType("integer");

                    b.Property<int>("ViewId")
                        .HasColumnType("integer");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<int?>("SheetId")
                        .HasColumnType("integer");

                    b.HasKey("RvtSnapshotId", "ElementId", "ViewId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SheetId");

                    b.HasIndex("RvtSnapshotId", "ViewId");

                    b.ToTable("ElementViews");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Error", b =>
                {
                    b.Property<Guid>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ErrorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.HasKey("RvtSnapshotId", "Id");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Grid", b =>
                {
                    b.Property<Guid?>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int>("GridId")
                        .HasColumnType("integer");

                    b.Property<string>("GridUniqueId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("RvtSnapshotId", "GridId");

                    b.ToTable("Grids");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Level", b =>
                {
                    b.Property<Guid?>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("ElevationValue")
                        .HasColumnType("text");

                    b.Property<string>("LevelUniqueId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("RvtSnapshotId", "LevelId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Material", b =>
                {
                    b.Property<Guid?>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialUniqueId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("RvtSnapshotId", "MaterialId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Parameter", b =>
                {
                    b.Property<Guid>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParameterGUID")
                        .HasColumnType("uuid");

                    b.Property<int?>("ParameterId")
                        .HasColumnType("integer");

                    b.HasKey("RvtSnapshotId", "Id");

                    b.HasIndex("RvtSnapshotId", "ParameterGUID")
                        .IsUnique();

                    b.HasIndex("RvtSnapshotId", "ParameterId")
                        .IsUnique();

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.ProjectsCategories", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId1")
                        .HasColumnType("integer");

                    b.Property<Guid>("CategoryRvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "CategoryId");

                    b.HasIndex("RvtSnapshotId");

                    b.HasIndex("CategoryRvtSnapshotId", "CategoryId1");

                    b.ToTable("ProjectsCategories");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.RvtDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Building")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Discipline")
                        .HasColumnType("text");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectName")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("RvtDocuments");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Schedule", b =>
                {
                    b.Property<int?>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("ScheduleId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScheduleUniqueId")
                        .HasColumnType("text");

                    b.HasKey("ScheduleId");

                    b.HasIndex("RvtSnapshotId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.ScheduleFilter", b =>
                {
                    b.Property<int>("ScheduleFilterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleFilterId"));

                    b.Property<string>("FilterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParameterRefGuid")
                        .HasColumnType("text");

                    b.Property<int?>("ParameterRefId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<string>("ScheduleUniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SystemParameterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SystemParameterRvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ScheduleFilterId");

                    b.HasIndex("RvtSnapshotId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SystemParameterRvtSnapshotId", "SystemParameterId");

                    b.ToTable("ScheduleFilter");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Sheet", b =>
                {
                    b.Property<int?>("SheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("SheetId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("SheetUniqueId")
                        .HasColumnType("text");

                    b.HasKey("SheetId");

                    b.HasIndex("RvtSnapshotId");

                    b.ToTable("Sheets");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Site", b =>
                {
                    b.Property<int?>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("SiteId"));

                    b.Property<string>("BasePointAngle")
                        .HasColumnType("text");

                    b.Property<string>("BasePointEastWest")
                        .HasColumnType("text");

                    b.Property<string>("BasePointElevetionValue")
                        .HasColumnType("text");

                    b.Property<string>("BasePointNorthSouth")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Latitude")
                        .HasColumnType("text");

                    b.Property<string>("Longitude")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiteUniqueId")
                        .HasColumnType("text");

                    b.HasKey("SiteId");

                    b.HasIndex("RvtSnapshotId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Stage", b =>
                {
                    b.Property<Guid?>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("StageUniqueId")
                        .HasColumnType("text");

                    b.HasKey("RvtSnapshotId", "StageId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.View", b =>
                {
                    b.Property<Guid?>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ViewId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ViewUniqueId")
                        .HasColumnType("text");

                    b.HasKey("RvtSnapshotId", "ViewId");

                    b.ToTable("Views");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Workset", b =>
                {
                    b.Property<Guid?>("RvtSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WorksetId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("WorksetUniqueId")
                        .HasColumnType("text");

                    b.HasKey("RvtSnapshotId", "WorksetId");

                    b.ToTable("Worksets");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Category", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("Categories")
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.DesignOption", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("DesignOptions")
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Element", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("Elements")
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Category", "Category")
                        .WithMany("Elements")
                        .HasForeignKey("RvtSnapshotId", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.DesignOption", "DesignOption")
                        .WithMany("Elements")
                        .HasForeignKey("RvtSnapshotId", "DesignOptionId");

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Level", "Level")
                        .WithMany("Elements")
                        .HasForeignKey("RvtSnapshotId", "LevelId");

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Stage", "Stage")
                        .WithMany("Elements")
                        .HasForeignKey("RvtSnapshotId", "StageId");

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Workset", "Workset")
                        .WithMany("Elements")
                        .HasForeignKey("RvtSnapshotId", "WorksetId");

                    b.Navigation("Category");

                    b.Navigation("DesignOption");

                    b.Navigation("Level");

                    b.Navigation("RvtSnapshot");

                    b.Navigation("Stage");

                    b.Navigation("Workset");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.ElementError", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany()
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Element", "Element")
                        .WithMany("Errors")
                        .HasForeignKey("RvtSnapshotId", "ElementId");

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Error", "Error")
                        .WithMany("Errors")
                        .HasForeignKey("RvtSnapshotId", "ErrorId");

                    b.Navigation("Element");

                    b.Navigation("Error");

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.ElementMaterial", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany()
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Element", "Element")
                        .WithMany("ElementMaterials")
                        .HasForeignKey("RvtSnapshotId", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Material", "Material")
                        .WithMany("ElementMaterials")
                        .HasForeignKey("RvtSnapshotId", "MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Material");

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.ElementParameterValue", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany()
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Element", "Element")
                        .WithMany("Parameters")
                        .HasForeignKey("RvtSnapshotId", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Parameter", "Parameter")
                        .WithMany("ElementLinks")
                        .HasForeignKey("RvtSnapshotId", "ParameterDbId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Element");

                    b.Navigation("Parameter");

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.ElementView", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany()
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Schedule", null)
                        .WithMany("ElementViews")
                        .HasForeignKey("ScheduleId");

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Sheet", null)
                        .WithMany("ElementViews")
                        .HasForeignKey("SheetId");

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Element", "Element")
                        .WithMany("ElementViews")
                        .HasForeignKey("RvtSnapshotId", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.View", "View")
                        .WithMany("ElementViews")
                        .HasForeignKey("RvtSnapshotId", "ViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("RvtSnapshot");

                    b.Navigation("View");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Error", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("Errors")
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Grid", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("Grids")
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Level", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("Levels")
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Material", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("Materials")
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Parameter", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("Parameters")
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.ProjectsCategories", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany()
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryRvtSnapshotId", "CategoryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.RvtDocument", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Author", "Author")
                        .WithMany("Documents")
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtDocument", "Document")
                        .WithMany("Snapshots")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Schedule", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("Schedules")
                        .HasForeignKey("RvtSnapshotId");

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.ScheduleFilter", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", null)
                        .WithMany("ScheduleFilters")
                        .HasForeignKey("RvtSnapshotId");

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.Parameter", "SystemParameter")
                        .WithMany()
                        .HasForeignKey("SystemParameterRvtSnapshotId", "SystemParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("SystemParameter");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Sheet", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("Sheets")
                        .HasForeignKey("RvtSnapshotId");

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Site", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("Sites")
                        .HasForeignKey("RvtSnapshotId");

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Stage", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("Stages")
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.View", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("Views")
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Workset", b =>
                {
                    b.HasOne("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", "RvtSnapshot")
                        .WithMany("Worksets")
                        .HasForeignKey("RvtSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RvtSnapshot");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Author", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Category", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.DesignOption", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Element", b =>
                {
                    b.Navigation("ElementMaterials");

                    b.Navigation("ElementViews");

                    b.Navigation("Errors");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Error", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Level", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Material", b =>
                {
                    b.Navigation("ElementMaterials");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Parameter", b =>
                {
                    b.Navigation("ElementLinks");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.RvtDocument", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.RvtSnapshot", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("DesignOptions");

                    b.Navigation("Elements");

                    b.Navigation("Errors");

                    b.Navigation("Grids");

                    b.Navigation("Levels");

                    b.Navigation("Materials");

                    b.Navigation("Parameters");

                    b.Navigation("ScheduleFilters");

                    b.Navigation("Schedules");

                    b.Navigation("Sheets");

                    b.Navigation("Sites");

                    b.Navigation("Stages");

                    b.Navigation("Views");

                    b.Navigation("Worksets");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Schedule", b =>
                {
                    b.Navigation("ElementViews");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Sheet", b =>
                {
                    b.Navigation("ElementViews");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Stage", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.View", b =>
                {
                    b.Navigation("ElementViews");
                });

            modelBuilder.Entity("BuildOpsPlatform.RevitDataService.Models.Workset", b =>
                {
                    b.Navigation("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
